<a href="https://colab.research.google.com/github/eugeniohdez05/Laboratorio-de-aprendizaje-estadistico/blob/main/Clase_bootstrap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
ಥ_ಥ= files.upload()

Saving Motor Trend Car Road Tests.xlsx to Motor Trend Car Road Tests.xlsx

In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np
import statsmodels.api as sm
import random
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
df = pd.read_excel("Motor Trend Car Road Tests.xlsx")
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [4]:
lr= LinearRegression()
X= df[['hp', 'qsec']]
y= df['mpg']

In [5]:
lr.fit(X,y)

LinearRegression()

In [6]:
B0= lr.intercept_
B1= lr.coef_[0]
B2= lr.coef_[1]
print(f'B0 = {B0}')
print(f'B1 = {B1}')
print(f'B2 = {B2}')

B0 = 48.32370516913444
B1 = -0.0845930436740927
B2 = -0.886579624634272

In [7]:
#Usando ols
X = sm.add_constant(X)
model=sm.OLS(y, X) # -> Modela minimos cuadrados ordinarios con todas las variables
results=model.fit() #-> Optimiza
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.637
Model:                            OLS   Adj. R-squared:                  0.612
Method:                 Least Squares   F-statistic:                     25.43
Date:                Thu, 30 Apr 2026   Prob (F-statistic):           4.18e-07
Time:                        22:41:49   Log-Likelihood:                -86.170
No. Observations:                  32   AIC:                             178.3
Df Residuals:                      29   BIC:                             182.7
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         48.3237     11.103      4.352      0.000      25.615      71.033
hp            -0.0846      0.014     -6.071      0.000      -0.113      -0.056
qsec          -0.8866      0.535     -1.658      0.108      -1.980       0.207
==============================================================================
Omnibus:                        5.102   Durbin-Watson:                   1.355
Prob(Omnibus):                  0.078   Jarque-Bera (JB):                3.987
Skew:                           0.858   Prob(JB):                        0.136
Kurtosis:                       3.220   Cond. No.                     2.72e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.72e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [8]:
B0= results.bse[0]
B1= results.bse[1]
B2= results.bse[2]
print(f'B0 = {B0}')
print(f'B1 = {B1}')
print(f'B2 = {B2}')

B0 = 11.103306326307141
B1 = 0.01393281448413601
B2 = 0.5345853790232801

In [9]:
#Intervalo de confianza
results.conf_int(alpha=0.05, cols=None)

               0          1
const  25.614894  71.032516
hp     -0.113089  -0.056097
qsec   -1.979929   0.206770

In [14]:
B0=[]
B1=[]
B2=[]
for i in range (1001):
  df_boot= df.sample(df.shape[0], replace=True)
  X= df_boot[['hp', 'qsec']]
  y= df_boot['mpg']
  X= sm.add_constant(X)
  model=sm.OLS(y, X)
  results=model.fit()
  #guardar cada regresión
  B0.append(results.bse[0])
  B1.append(results.bse[1])
  B2.append(results.bse[2])

# Aggregating

In [48]:
modelos = []
R2 = []
vars= []
models_test = []

In [49]:

for i in range (1001):
  available_features = ['cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
  random_cols = random.sample(available_features, 3)
  X = df[random_cols]
  y = df['mpg']
  X= sm.add_constant(X)
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
  model=sm.OLS(y_train, X_train)
  results=model.fit()
  modelos += [results]
  vars.append(random_cols)
  results_test= results.predict(X_test)
  models_test.append(results_test)

In [61]:
y_test= np.array(y_test).reshape(-1,1)

In [63]:
mean_models_test= np.mean(models_test, axis=0)
mean_models_test= np.array(mean_models_test).reshape(-1,1)
mean_models_test
R2= r2_score(y_test, mean_models_test)
R2

0.7820204935094301